<?php

namespace Tests;

use Illuminate\Foundation\Testing\TestCase as BaseTestCase;
use Illuminate\Support\Facades\Artisan;

abstract class TestCase extends BaseTestCase
{
    use CreatesApplication;

    protected static $migrationsRun = false;

    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        if (!static::$migrationsRun) {
            Artisan::call('migrate:fresh');
            Artisan::call('db:seed');
            static::$migrationsRun = true;
        }
    }
}
